import colors from '../colors';

export const footerStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    padding: '16px 20px 20px 20px',
    backgroundColor: colors.background,
    borderTop: 'none',
    flexShrink: 0,
  },
  primaryButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '52px',
    border: 'none',
    borderRadius: '16px',
    backgroundColor: colors.buttonDark,
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 2px 8px rgba(79, 70, 229, 0.15), 0 1px 2px rgba(79, 70, 229, 0.1)',
  },
  primaryButtonHover: {
    backgroundColor: colors.buttonHover,
    transform: 'translateY(-1px)',
    boxShadow: '0 4px 12px rgba(79, 70, 229, 0.2), 0 2px 4px rgba(79, 70, 229, 0.15)',
  },
  secondaryButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '40px',
    border: 'none',
    borderRadius: '0',
    backgroundColor: 'transparent',
    color: '#9ca3af',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'color 0.2s ease',
  },
  secondaryButtonHover: {
    color: '#6b7280',
  },
};
